### ISSUE TITLE
Button state not automatically updated in Home

### ISSUE THREAD

**Issue by rdouma** [adyanth/homebridge-plugin-command#1]
If the button state gets changed from another device or an automation, the button state doesn't get updated in Apple Home without reloading that page. Once I switch pages and come back the button state is correct, but it seems there is no "push" of the button's status to Homekit once it's changed.

**Comment by adyanth** [comment]
Nice catch! Yes, there is no push yet. I would need to add a polling time to the input and run the status check command to see if it changes.

**Comment by rdouma** [comment]
Sounds like a plan :-D

**Comment by adyanth** [comment]
Quick question if you don't mind me asking, how did you configure the plugin? Did you use the sample from the ReadMe or use the GUI to configure it?

**Comment by rdouma** [comment]
Sure, no problem at all! I used the GUI to configure it.

**Comment by adyanth** [comment]
The reason I ask is because I was running into this issue trying to configure via GUI myself! https://github.com/oznu/homebridge-config-ui-x/issues/1448

Was it version v1.0.1 or v1.0.2?

**Comment by rdouma** [comment]
It's version v1.0.22.

**Comment by adyanth** [comment]
Oh, are you using the homebridge-plugin-command-dev? I would recommend switching over to homebridge-plugin-command now. That was for testing these changes before I published to the main package :)

**Comment by rdouma** [comment]
Ah sure, no problem! Don't remember how I came to install homebridge-plugin-command-dev. Is that for internal tests?

**Comment by adyanth** [comment]
It was for me to iteratively test it on my homebridge since I could not develop on the device haha.

**Comment by rdouma** [comment]
Ah!! It came up while searching for plugins in Homebridge. Was wondering about the dev lol.

**Comment by rdouma** [comment]
Was testing it now with 2 computers and a phone, pressing the switches on the phone. On one computer it switches along. On the other one it doesn't; there I need to refresh. Situation:

1. Press buttons on phone, desktop switches but MBP doesn't.
2. Press buttons on desktop: phone switches but MBP doesn't.
3. Press buttons on MBP: desktop and phone switches.

Any idea how this can be? I tried quitting and restarting Home on the MBP but to no avail.

**Comment by adyanth** [comment]
Yeah, I can reproduce that myself. My iPad, which is configured as a home hub, switches perfectly every single time, but my phone and laptop need a refresh to see the change.

Since I can reproduce this issue with my TP-Link smart home switch, this is not isolated to just this plugin. Weird, maybe try asking in the home bridge GitHub/reddit?

Edit: I only tested the polling, let me check the use case you mentioned exactly and get back to you.

**Comment by adyanth** [comment]
Okay, yes. My Mac does not switch for this plugin when triggered by the phone, but TP-Link does. Let me look into this a bit further. But, the poll issue still stands.

**Comment by rdouma** [comment]
Ok, I don't have TP Link but I don't recall seeing this behavior with my Philips Hue... Thanks for looking into it 🙏
