### ISSUE TITLE
State check options

### ISSUE THREAD

**Issue by im-L0r3** [adyanth/homebridge-plugin-command#8]
Thanks for this plugin. Works perfect and lets me run BASH script, prtty much making HomeKit actions unlimited.

Question... Can I set the on/off result of a state check by reading the contents of a file?
For example if I put a 0 or a 1 in the file?

I have tried cat /someFile, and that file contains 'exit 1' but of course the catting itself was successful so thats what generates the 0.

**Comment by adyanth** [comment]
If the file contains "exit 0", you can run the file with "bash filename". If it contains 0/1, you can try something like "cat file | xargs exit"

**Comment by im-L0r3** [comment]
Thanks for the fast response!

This works perfect:

Command to check status:
bash /pathToSomeFile.sh

Then for the contents of the file:
- "exit 0" tells HomeKit the accessory is on
- "exit 1" tells HomeKit the accessory is off
